export const GET_SHOW = 'GET_SHOW';
export const UNMOUNT_SHOW = 'UNMOUNT_SHOW';
export const UPDATE_QUERY = 'UPDATE_QUERY';
export const FETCH_SERIES_LIST = 'FETCH_SERIES_LIST';
export const SAVE_SERIES = 'SAVE_SERIES';
export const REMOVE_SAVED_SERIES = 'REMOVE_SAVED_SERIES';